// Country data for Countries Trivia.
// Each row: [iso2 code, name, capital, level, region, countryAliases, capitalAliases]
// Levels: 1 = world-famous ... 5 = obscure territories & islands.
// region: geographical location used for hard-mode hints.
const COUNTRY_ROWS = [
  // ---------- Level 1: very well-known countries ----------
  ["us", "United States", "Washington, D.C.", 1, "North America", ["USA", "US", "America", "United States of America"], ["Washington DC", "Washington"]],
  ["gb", "United Kingdom", "London", 1, "Western Europe", ["UK", "Great Britain", "Britain"], []],
  ["fr", "France", "Paris", 1, "Western Europe", [], []],
  ["de", "Germany", "Berlin", 1, "Central Europe", [], []],
  ["it", "Italy", "Rome", 1, "Southern Europe", [], ["Roma"]],
  ["es", "Spain", "Madrid", 1, "Southern Europe", [], []],
  ["pt", "Portugal", "Lisbon", 1, "Southern Europe", [], ["Lisboa"]],
  ["ca", "Canada", "Ottawa", 1, "North America", [], []],
  ["mx", "Mexico", "Mexico City", 1, "North America", [], ["Ciudad de Mexico", "CDMX"]],
  ["br", "Brazil", "Brasília", 1, "South America", [], ["Brasilia"]],
  ["ar", "Argentina", "Buenos Aires", 1, "South America", [], []],
  ["ru", "Russia", "Moscow", 1, "Eastern Europe / North Asia", ["Russian Federation"], []],
  ["cn", "China", "Beijing", 1, "East Asia", ["People's Republic of China"], ["Peking"]],
  ["jp", "Japan", "Tokyo", 1, "East Asia", [], []],
  ["in", "India", "New Delhi", 1, "South Asia", [], ["Delhi"]],
  ["au", "Australia", "Canberra", 1, "Oceania", [], []],
  ["eg", "Egypt", "Cairo", 1, "North Africa", [], []],
  ["za", "South Africa", "Pretoria", 1, "Southern Africa", [], ["Cape Town", "Bloemfontein"]],
  ["gr", "Greece", "Athens", 1, "Southern Europe (Balkans)", [], []],
  ["tr", "Turkey", "Ankara", 1, "between Europe and the Middle East", ["Turkiye", "Türkiye"], []],
  ["nl", "Netherlands", "Amsterdam", 1, "Western Europe", ["Holland", "The Netherlands"], []],
  ["ch", "Switzerland", "Bern", 1, "Central Europe (the Alps)", [], ["Berne"]],
  ["se", "Sweden", "Stockholm", 1, "Northern Europe (Scandinavia)", [], []],
  ["no", "Norway", "Oslo", 1, "Northern Europe (Scandinavia)", [], []],
  ["ie", "Ireland", "Dublin", 1, "Western Europe (British Isles)", [], []],
  ["pl", "Poland", "Warsaw", 1, "Central Europe", [], ["Warszawa"]],
  ["kr", "South Korea", "Seoul", 1, "East Asia", ["Korea", "Republic of Korea"], []],
  ["sa", "Saudi Arabia", "Riyadh", 1, "Middle East (Arabian Peninsula)", [], []],
  ["il", "Israel", "Jerusalem", 1, "Middle East", [], []],
  ["nz", "New Zealand", "Wellington", 1, "Oceania (South Pacific)", [], []],

  // ---------- Level 2: well-known countries ----------
  ["at", "Austria", "Vienna", 2, "Central Europe (the Alps)", [], ["Wien"]],
  ["be", "Belgium", "Brussels", 2, "Western Europe", [], ["Bruxelles"]],
  ["dk", "Denmark", "Copenhagen", 2, "Northern Europe (Scandinavia)", [], []],
  ["fi", "Finland", "Helsinki", 2, "Northern Europe (Nordics)", [], []],
  ["is", "Iceland", "Reykjavik", 2, "Northern Europe (North Atlantic island)", [], ["Reykjavík"]],
  ["ua", "Ukraine", "Kyiv", 2, "Eastern Europe", [], ["Kiev"]],
  ["cz", "Czechia", "Prague", 2, "Central Europe", ["Czech Republic"], ["Praha"]],
  ["hu", "Hungary", "Budapest", 2, "Central Europe", [], []],
  ["ro", "Romania", "Bucharest", 2, "Eastern Europe", [], []],
  ["hr", "Croatia", "Zagreb", 2, "Southern Europe (Balkans, Adriatic coast)", [], []],
  ["cu", "Cuba", "Havana", 2, "the Caribbean", [], ["La Habana"]],
  ["co", "Colombia", "Bogotá", 2, "South America", [], ["Bogota"]],
  ["cl", "Chile", "Santiago", 2, "South America (Pacific coast)", [], []],
  ["pe", "Peru", "Lima", 2, "South America (Andes)", [], []],
  ["ve", "Venezuela", "Caracas", 2, "South America (Caribbean coast)", [], []],
  ["th", "Thailand", "Bangkok", 2, "Southeast Asia", [], []],
  ["vn", "Vietnam", "Hanoi", 2, "Southeast Asia", [], []],
  ["ph", "Philippines", "Manila", 2, "Southeast Asia (Pacific archipelago)", ["The Philippines"], []],
  ["id", "Indonesia", "Jakarta", 2, "Southeast Asia (archipelago)", [], []],
  ["my", "Malaysia", "Kuala Lumpur", 2, "Southeast Asia", [], ["KL"]],
  ["sg", "Singapore", "Singapore", 2, "Southeast Asia (city-state)", [], ["Singapore City"]],
  ["pk", "Pakistan", "Islamabad", 2, "South Asia", [], []],
  ["ir", "Iran", "Tehran", 2, "Middle East", [], []],
  ["iq", "Iraq", "Baghdad", 2, "Middle East", [], []],
  ["ma", "Morocco", "Rabat", 2, "North Africa (Maghreb)", [], []],
  ["dz", "Algeria", "Algiers", 2, "North Africa (Maghreb)", [], []],
  ["tn", "Tunisia", "Tunis", 2, "North Africa (Maghreb)", [], []],
  ["ng", "Nigeria", "Abuja", 2, "West Africa", [], []],
  ["ke", "Kenya", "Nairobi", 2, "East Africa", [], []],
  ["et", "Ethiopia", "Addis Ababa", 2, "East Africa (Horn of Africa)", [], []],
  ["ae", "United Arab Emirates", "Abu Dhabi", 2, "Middle East (Persian Gulf)", ["UAE", "Emirates"], []],
  ["qa", "Qatar", "Doha", 2, "Middle East (Persian Gulf)", [], []],
  ["jm", "Jamaica", "Kingston", 2, "the Caribbean", [], []],
  ["ec", "Ecuador", "Quito", 2, "South America (Andes, on the equator)", [], []],
  ["uy", "Uruguay", "Montevideo", 2, "South America (Atlantic coast)", [], []],
  ["bg", "Bulgaria", "Sofia", 2, "Eastern Europe (Balkans)", [], []],
  ["rs", "Serbia", "Belgrade", 2, "Southern Europe (Balkans)", [], ["Beograd"]],
  ["sk", "Slovakia", "Bratislava", 2, "Central Europe", [], []],
  ["kp", "North Korea", "Pyongyang", 2, "East Asia", ["Democratic People's Republic of Korea", "DPRK"], []],
  ["af", "Afghanistan", "Kabul", 2, "Central / South Asia", [], []],

  // ---------- Level 3: moderately known countries ----------
  ["bo", "Bolivia", "Sucre", 3, "South America (Andes, landlocked)", [], ["La Paz"]],
  ["py", "Paraguay", "Asunción", 3, "South America (landlocked)", [], ["Asuncion"]],
  ["gt", "Guatemala", "Guatemala City", 3, "Central America", [], ["Guatemala"]],
  ["hn", "Honduras", "Tegucigalpa", 3, "Central America", [], []],
  ["ni", "Nicaragua", "Managua", 3, "Central America", [], []],
  ["cr", "Costa Rica", "San José", 3, "Central America", [], ["San Jose"]],
  ["pa", "Panama", "Panama City", 3, "Central America", [], ["Panama"]],
  ["do", "Dominican Republic", "Santo Domingo", 3, "the Caribbean (island of Hispaniola)", [], []],
  ["ht", "Haiti", "Port-au-Prince", 3, "the Caribbean (island of Hispaniola)", [], []],
  ["sv", "El Salvador", "San Salvador", 3, "Central America", [], []],
  ["si", "Slovenia", "Ljubljana", 3, "Central Europe (Alps / Adriatic)", [], []],
  ["lt", "Lithuania", "Vilnius", 3, "Northern Europe (the Baltics)", [], []],
  ["lv", "Latvia", "Riga", 3, "Northern Europe (the Baltics)", [], []],
  ["ee", "Estonia", "Tallinn", 3, "Northern Europe (the Baltics)", [], []],
  ["by", "Belarus", "Minsk", 3, "Eastern Europe", [], []],
  ["al", "Albania", "Tirana", 3, "Southern Europe (Balkans, Adriatic coast)", [], ["Tirane"]],
  ["ba", "Bosnia and Herzegovina", "Sarajevo", 3, "Southern Europe (Balkans)", ["Bosnia"], []],
  ["mk", "North Macedonia", "Skopje", 3, "Southern Europe (Balkans)", ["Macedonia"], []],
  ["md", "Moldova", "Chișinău", 3, "Eastern Europe", [], ["Chisinau", "Kishinev"]],
  ["ge", "Georgia", "Tbilisi", 3, "the Caucasus", [], []],
  ["am", "Armenia", "Yerevan", 3, "the Caucasus", [], []],
  ["az", "Azerbaijan", "Baku", 3, "the Caucasus (Caspian Sea)", [], []],
  ["kz", "Kazakhstan", "Astana", 3, "Central Asia", [], ["Nur-Sultan"]],
  ["uz", "Uzbekistan", "Tashkent", 3, "Central Asia", [], []],
  ["mn", "Mongolia", "Ulaanbaatar", 3, "East / Central Asia (landlocked steppe)", [], ["Ulan Bator"]],
  ["np", "Nepal", "Kathmandu", 3, "South Asia (Himalayas)", [], []],
  ["lk", "Sri Lanka", "Sri Jayawardenepura Kotte", 3, "South Asia (Indian Ocean island)", [], ["Colombo", "Kotte"]],
  ["bd", "Bangladesh", "Dhaka", 3, "South Asia", [], []],
  ["mm", "Myanmar", "Naypyidaw", 3, "Southeast Asia", ["Burma"], ["Nay Pyi Taw"]],
  ["kh", "Cambodia", "Phnom Penh", 3, "Southeast Asia", [], []],
  ["la", "Laos", "Vientiane", 3, "Southeast Asia (landlocked)", [], []],
  ["jo", "Jordan", "Amman", 3, "Middle East (Levant)", [], []],
  ["lb", "Lebanon", "Beirut", 3, "Middle East (Levant, Mediterranean coast)", [], []],
  ["sy", "Syria", "Damascus", 3, "Middle East (Levant)", [], []],
  ["ye", "Yemen", "Sanaa", 3, "Middle East (southern Arabian Peninsula)", [], ["Sana'a"]],
  ["om", "Oman", "Muscat", 3, "Middle East (Arabian Peninsula)", [], []],
  ["kw", "Kuwait", "Kuwait City", 3, "Middle East (Persian Gulf)", [], ["Kuwait"]],
  ["bh", "Bahrain", "Manama", 3, "Middle East (Persian Gulf island)", [], []],
  ["ly", "Libya", "Tripoli", 3, "North Africa", [], []],
  ["sd", "Sudan", "Khartoum", 3, "Northeast Africa", [], []],
  ["gh", "Ghana", "Accra", 3, "West Africa (Gulf of Guinea)", [], []],
  ["sn", "Senegal", "Dakar", 3, "West Africa (Atlantic coast)", [], []],
  ["ci", "Ivory Coast", "Yamoussoukro", 3, "West Africa (Gulf of Guinea)", ["Cote d'Ivoire", "Côte d'Ivoire"], ["Abidjan"]],
  ["cm", "Cameroon", "Yaoundé", 3, "Central Africa", [], ["Yaounde"]],
  ["tz", "Tanzania", "Dodoma", 3, "East Africa", [], ["Dar es Salaam"]],
  ["ug", "Uganda", "Kampala", 3, "East Africa", [], []],
  ["zw", "Zimbabwe", "Harare", 3, "Southern Africa (landlocked)", [], []],
  ["zm", "Zambia", "Lusaka", 3, "Southern Africa (landlocked)", [], []],
  ["ao", "Angola", "Luanda", 3, "Southern Africa (Atlantic coast)", [], []],
  ["mz", "Mozambique", "Maputo", 3, "Southern Africa (Indian Ocean coast)", [], []],
  ["mg", "Madagascar", "Antananarivo", 3, "Indian Ocean (island off East Africa)", [], []],
  ["lu", "Luxembourg", "Luxembourg City", 3, "Western Europe", [], ["Luxembourg"]],
  ["mt", "Malta", "Valletta", 3, "the Mediterranean (island south of Italy)", [], []],
  ["cy", "Cyprus", "Nicosia", 3, "the eastern Mediterranean", [], []],
  ["fj", "Fiji", "Suva", 3, "the South Pacific", [], []],

  // ---------- Level 4: lesser-known countries ----------
  ["bt", "Bhutan", "Thimphu", 4, "South Asia (Himalayas)", [], []],
  ["bn", "Brunei", "Bandar Seri Begawan", 4, "Southeast Asia (island of Borneo)", [], []],
  ["mv", "Maldives", "Malé", 4, "the Indian Ocean (atoll nation)", [], ["Male"]],
  ["tl", "Timor-Leste", "Dili", 4, "Southeast Asia", ["East Timor"], []],
  ["pg", "Papua New Guinea", "Port Moresby", 4, "Oceania (southwest Pacific)", ["PNG"], []],
  ["tj", "Tajikistan", "Dushanbe", 4, "Central Asia", [], []],
  ["kg", "Kyrgyzstan", "Bishkek", 4, "Central Asia", [], []],
  ["tm", "Turkmenistan", "Ashgabat", 4, "Central Asia (Caspian Sea)", [], []],
  ["me", "Montenegro", "Podgorica", 4, "Southern Europe (Balkans, Adriatic coast)", [], []],
  ["xk", "Kosovo", "Pristina", 4, "Southern Europe (Balkans)", [], ["Prishtina"]],
  ["ad", "Andorra", "Andorra la Vella", 4, "Europe (the Pyrenees, between France and Spain)", [], []],
  ["mc", "Monaco", "Monaco", 4, "Europe (French Riviera)", [], ["Monaco-Ville"]],
  ["li", "Liechtenstein", "Vaduz", 4, "Europe (the Alps, between Switzerland and Austria)", [], []],
  ["sm", "San Marino", "San Marino", 4, "Europe (enclave inside Italy)", [], ["City of San Marino"]],
  ["va", "Vatican City", "Vatican City", 4, "Europe (enclave inside Rome)", ["Holy See", "The Vatican"], []],
  ["bw", "Botswana", "Gaborone", 4, "Southern Africa (Kalahari)", [], []],
  ["na", "Namibia", "Windhoek", 4, "Southern Africa (Atlantic coast)", [], []],
  ["rw", "Rwanda", "Kigali", 4, "East Africa (Great Lakes)", [], []],
  ["bi", "Burundi", "Gitega", 4, "East Africa (Great Lakes)", [], ["Bujumbura"]],
  ["mw", "Malawi", "Lilongwe", 4, "Southern / East Africa (Lake Malawi)", [], []],
  ["ml", "Mali", "Bamako", 4, "West Africa (Sahel)", [], []],
  ["ne", "Niger", "Niamey", 4, "West Africa (Sahel)", [], []],
  ["td", "Chad", "N'Djamena", 4, "Central Africa (Sahel)", [], ["Ndjamena"]],
  ["mr", "Mauritania", "Nouakchott", 4, "West Africa (Sahara, Atlantic coast)", [], []],
  ["bf", "Burkina Faso", "Ouagadougou", 4, "West Africa (Sahel)", [], []],
  ["bj", "Benin", "Porto-Novo", 4, "West Africa (Gulf of Guinea)", [], ["Cotonou"]],
  ["tg", "Togo", "Lomé", 4, "West Africa (Gulf of Guinea)", [], ["Lome"]],
  ["gn", "Guinea", "Conakry", 4, "West Africa (Atlantic coast)", [], []],
  ["sl", "Sierra Leone", "Freetown", 4, "West Africa (Atlantic coast)", [], []],
  ["lr", "Liberia", "Monrovia", 4, "West Africa (Atlantic coast)", [], []],
  ["ga", "Gabon", "Libreville", 4, "Central Africa (on the equator)", [], []],
  ["cg", "Republic of the Congo", "Brazzaville", 4, "Central Africa", ["Congo", "Congo-Brazzaville"], []],
  ["cd", "DR Congo", "Kinshasa", 4, "Central Africa", ["Democratic Republic of the Congo", "DRC", "Congo-Kinshasa"], []],
  ["cf", "Central African Republic", "Bangui", 4, "Central Africa", ["CAR"], []],
  ["so", "Somalia", "Mogadishu", 4, "East Africa (Horn of Africa)", [], []],
  ["er", "Eritrea", "Asmara", 4, "East Africa (Horn of Africa, Red Sea)", [], []],
  ["dj", "Djibouti", "Djibouti City", 4, "East Africa (Horn of Africa, Red Sea)", [], ["Djibouti"]],
  ["ss", "South Sudan", "Juba", 4, "East Africa", [], []],
  ["gm", "Gambia", "Banjul", 4, "West Africa (enclave within Senegal)", ["The Gambia"], []],
  ["gw", "Guinea-Bissau", "Bissau", 4, "West Africa (Atlantic coast)", [], []],
  ["gq", "Equatorial Guinea", "Malabo", 4, "Central Africa (Gulf of Guinea)", [], []],
  ["sz", "Eswatini", "Mbabane", 4, "Southern Africa (landlocked)", ["Swaziland"], ["Lobamba"]],
  ["ls", "Lesotho", "Maseru", 4, "Southern Africa (enclave inside South Africa)", [], []],
  ["mu", "Mauritius", "Port Louis", 4, "the Indian Ocean (island east of Madagascar)", [], []],
  ["sc", "Seychelles", "Victoria", 4, "the Indian Ocean (archipelago)", [], []],
  ["cv", "Cape Verde", "Praia", 4, "the Atlantic (islands off West Africa)", ["Cabo Verde"], []],
  ["km", "Comoros", "Moroni", 4, "the Indian Ocean (islands near Madagascar)", [], []],
  ["st", "São Tomé and Príncipe", "São Tomé", 4, "the Gulf of Guinea (islands off Central Africa)", ["Sao Tome and Principe"], ["Sao Tome"]],
  ["bz", "Belize", "Belmopan", 4, "Central America (Caribbean coast)", [], []],
  ["gy", "Guyana", "Georgetown", 4, "South America (Caribbean coast)", [], []],
  ["sr", "Suriname", "Paramaribo", 4, "South America (Caribbean coast)", [], []],
  ["tt", "Trinidad and Tobago", "Port of Spain", 4, "the Caribbean (off Venezuela)", ["Trinidad"], []],
  ["bs", "Bahamas", "Nassau", 4, "the Caribbean / North Atlantic", ["The Bahamas"], []],
  ["bb", "Barbados", "Bridgetown", 4, "the Caribbean (Lesser Antilles)", [], []],
  ["kn", "Saint Kitts and Nevis", "Basseterre", 4, "the Caribbean (Lesser Antilles)", ["St Kitts and Nevis"], []],
  ["lc", "Saint Lucia", "Castries", 4, "the Caribbean (Lesser Antilles)", ["St Lucia"], []],
  ["vc", "Saint Vincent and the Grenadines", "Kingstown", 4, "the Caribbean (Lesser Antilles)", ["St Vincent"], []],
  ["gd", "Grenada", "St. George's", 4, "the Caribbean (Lesser Antilles)", [], ["Saint George's", "St Georges"]],
  ["dm", "Dominica", "Roseau", 4, "the Caribbean (Lesser Antilles)", [], []],
  ["ag", "Antigua and Barbuda", "St. John's", 4, "the Caribbean (Lesser Antilles)", ["Antigua"], ["Saint John's", "St Johns"]],
  ["ws", "Samoa", "Apia", 4, "the South Pacific (Polynesia)", [], []],
  ["to", "Tonga", "Nuku'alofa", 4, "the South Pacific (Polynesia)", [], ["Nukualofa"]],
  ["vu", "Vanuatu", "Port Vila", 4, "the South Pacific (Melanesia)", [], []],
  ["sb", "Solomon Islands", "Honiara", 4, "the South Pacific (Melanesia)", [], []],

  // ---------- Level 5: obscure territories, islands & micro-states ----------
  ["tv", "Tuvalu", "Funafuti", 5, "the South Pacific (Polynesia, atoll nation)", [], []],
  ["nr", "Nauru", "Yaren", 5, "the Central Pacific (Micronesia)", [], []],
  ["ki", "Kiribati", "Tarawa", 5, "the Central Pacific (straddling the equator)", [], ["South Tarawa"]],
  ["pw", "Palau", "Ngerulmud", 5, "the Western Pacific (Micronesia)", [], []],
  ["mh", "Marshall Islands", "Majuro", 5, "the Central Pacific (Micronesia)", [], []],
  ["fm", "Micronesia", "Palikir", 5, "the Western Pacific", ["Federated States of Micronesia"], []],
  ["nu", "Niue", "Alofi", 5, "the South Pacific (Polynesia, near Tonga)", [], []],
  ["tk", "Tokelau", "Fakaofo", 5, "the South Pacific (Polynesian atolls)", [], ["Atafu", "Nukunonu"]],
  ["ck", "Cook Islands", "Avarua", 5, "the South Pacific (Polynesia)", [], []],
  ["pn", "Pitcairn Islands", "Adamstown", 5, "the remote South Pacific", ["Pitcairn"], []],
  ["wf", "Wallis and Futuna", "Mata-Utu", 5, "the South Pacific (Polynesia)", [], ["Mata Utu"]],
  ["pf", "French Polynesia", "Papeete", 5, "the South Pacific (Tahiti)", [], []],
  ["nc", "New Caledonia", "Nouméa", 5, "the South Pacific (Melanesia)", [], ["Noumea"]],
  ["nf", "Norfolk Island", "Kingston", 5, "the South Pacific (between Australia and New Zealand)", [], []],
  ["cx", "Christmas Island", "Flying Fish Cove", 5, "the Indian Ocean (south of Indonesia)", [], ["The Settlement"]],
  ["cc", "Cocos (Keeling) Islands", "West Island", 5, "the Indian Ocean (atolls southwest of Indonesia)", ["Cocos Islands", "Keeling Islands"], []],
  ["as", "American Samoa", "Pago Pago", 5, "the South Pacific (Polynesia)", [], []],
  ["gu", "Guam", "Hagåtña", 5, "the Western Pacific (Micronesia)", [], ["Hagatna", "Agana"]],
  ["mp", "Northern Mariana Islands", "Saipan", 5, "the Western Pacific (Micronesia)", [], []],
  ["sh", "Saint Helena", "Jamestown", 5, "the remote South Atlantic", ["St Helena"], []],
  ["fk", "Falkland Islands", "Stanley", 5, "the South Atlantic (off Argentina)", ["Falklands", "Malvinas"], ["Port Stanley"]],
  ["gs", "South Georgia and the South Sandwich Islands", "King Edward Point", 5, "the sub-Antarctic South Atlantic", ["South Georgia"], ["Grytviken"]],
  ["bm", "Bermuda", "Hamilton", 5, "the North Atlantic (off the US east coast)", [], []],
  ["ky", "Cayman Islands", "George Town", 5, "the Caribbean (south of Cuba)", [], ["Georgetown"]],
  ["tc", "Turks and Caicos Islands", "Cockburn Town", 5, "the Caribbean / North Atlantic", ["Turks and Caicos"], []],
  ["vg", "British Virgin Islands", "Road Town", 5, "the Caribbean (Virgin Islands)", ["BVI"], []],
  ["vi", "U.S. Virgin Islands", "Charlotte Amalie", 5, "the Caribbean (Virgin Islands)", ["US Virgin Islands", "United States Virgin Islands"], []],
  ["ai", "Anguilla", "The Valley", 5, "the Caribbean (Lesser Antilles)", [], []],
  ["ms", "Montserrat", "Brades", 5, "the Caribbean (Lesser Antilles)", [], ["Plymouth"]],
  ["aw", "Aruba", "Oranjestad", 5, "the southern Caribbean (off Venezuela)", [], []],
  ["cw", "Curaçao", "Willemstad", 5, "the southern Caribbean (off Venezuela)", ["Curacao"], []],
  ["sx", "Sint Maarten", "Philipsburg", 5, "the Caribbean (shared island with Saint Martin)", [], []],
  ["mf", "Saint Martin", "Marigot", 5, "the Caribbean (shared island with Sint Maarten)", ["St Martin"], []],
  ["bl", "Saint Barthélemy", "Gustavia", 5, "the Caribbean (Lesser Antilles)", ["St Barts", "Saint Barthelemy", "St Barthelemy"], []],
  ["pm", "Saint Pierre and Miquelon", "Saint-Pierre", 5, "the North Atlantic (off Newfoundland, Canada)", ["St Pierre and Miquelon"], ["Saint Pierre", "St Pierre"]],
  ["gl", "Greenland", "Nuuk", 5, "the Arctic / North Atlantic", [], ["Godthab", "Godthåb"]],
  ["fo", "Faroe Islands", "Tórshavn", 5, "the North Atlantic (between Iceland and Norway)", ["Faroes", "Faeroe Islands"], ["Torshavn"]],
  ["ax", "Åland Islands", "Mariehamn", 5, "the Baltic Sea (between Sweden and Finland)", ["Aland Islands", "Aland"], []],
  ["gi", "Gibraltar", "Gibraltar", 5, "the southern tip of the Iberian Peninsula", [], ["Westside"]],
  ["im", "Isle of Man", "Douglas", 5, "the Irish Sea (British Isles)", [], []],
  ["je", "Jersey", "Saint Helier", 5, "the Channel Islands (between England and France)", [], ["St Helier"]],
  ["gg", "Guernsey", "Saint Peter Port", 5, "the Channel Islands (between England and France)", [], ["St Peter Port"]],
  ["sj", "Svalbard", "Longyearbyen", 5, "the Arctic (far north of Norway)", ["Svalbard and Jan Mayen"], []],
  ["yt", "Mayotte", "Mamoudzou", 5, "the Indian Ocean (near the Comoros)", [], []],
  ["re", "Réunion", "Saint-Denis", 5, "the Indian Ocean (near Mauritius)", ["Reunion"], ["Saint Denis", "St Denis"]],
  ["mq", "Martinique", "Fort-de-France", 5, "the Caribbean (Lesser Antilles)", [], ["Fort de France"]],
  ["gp", "Guadeloupe", "Basse-Terre", 5, "the Caribbean (Lesser Antilles)", [], ["Basse Terre"]],
  ["gf", "French Guiana", "Cayenne", 5, "South America (Caribbean coast)", [], []],
  ["eh", "Western Sahara", "Laayoune", 5, "North Africa (Atlantic coast of the Sahara)", [], ["El Aaiun", "El Aaiún"]],
];

// ---------- point tiers ----------
// Points are tiered by how hard a country actually is to name, which is
// related to — but deliberately NOT locked to — its game level. Tiers are
// meant to be re-tuned over time from the per-country result stats the game
// records (see the Stats panel / JSON export): if a "hard" country is being
// guessed right nearly every time, demote its tier here.

const TIER_POINTS = { 1: 5, 2: 10, 3: 15, 4: 25, 5: 35, 6: 50, 7: 70, 8: 100 };

// default tier for each game level...
const BASE_TIER_BY_LEVEL = { 1: 1, 2: 3, 3: 4, 4: 6, 5: 7 };

// ...with per-country adjustments where recognisability doesn't match level.
const TIER_OVERRIDES = {
  // level 1 flags that are less iconic than their neighbours
  pt: 2, ie: 2, nz: 2, no: 2,
  // level 2 countries with very distinctive, widely known flags
  cu: 2, jm: 2, dk: 2, ua: 2, cz: 2,
  // level 2 countries with easily confused flags
  sk: 4, bg: 4, rs: 4, af: 4,
  // level 3 easier than average
  np: 3, mt: 3, cy: 3,
  // level 3 harder than average
  md: 5, mk: 5, ba: 5, la: 5,
  // level 4 with famous names or unmistakable flags
  va: 5, pg: 5, bt: 5, mu: 5,
  // level 4 genuinely tough
  cf: 7, gw: 7, km: 7,
  // level 5 territories most people have heard of
  gl: 6, gi: 6, bm: 6, aw: 6, pf: 6,
  // level 5 truly obscure — top tier
  pn: 8, tk: 8, wf: 8, nu: 8, gs: 8, cc: 8, cx: 8, sh: 8, pm: 8, mp: 8, ax: 8,
};

const COUNTRIES = COUNTRY_ROWS.map(([code, name, capital, level, region, aliases, capitalAliases]) => {
  const tier = TIER_OVERRIDES[code] || BASE_TIER_BY_LEVEL[level];
  return {
    code, name, capital, level, region, tier,
    points: TIER_POINTS[tier],
    aliases: aliases || [],
    capitalAliases: capitalAliases || [],
  };
});

const LEVEL_NAMES = {
  1: "Beginner",
  2: "Traveler",
  3: "Explorer",
  4: "Geographer",
  5: "Cartographer",
};

const LEVEL_HINTS = {
  1: "World-famous countries everyone knows",
  2: "Well-known countries",
  3: "Moderately known countries",
  4: "Lesser-known countries & micro-states",
  5: "Obscure territories & remote islands",
};
