// Country data for Countries Trivia.
// Each row: [iso2 code, name, capital, level, countryAliases, capitalAliases]
// Levels: 1 = world-famous ... 5 = obscure territories & islands.
const COUNTRY_ROWS = [
  // ---------- Level 1: very well-known countries ----------
  ["us", "United States", "Washington, D.C.", 1, ["USA", "US", "America", "United States of America"], ["Washington DC", "Washington"]],
  ["gb", "United Kingdom", "London", 1, ["UK", "Great Britain", "Britain"], []],
  ["fr", "France", "Paris", 1, [], []],
  ["de", "Germany", "Berlin", 1, [], []],
  ["it", "Italy", "Rome", 1, [], ["Roma"]],
  ["es", "Spain", "Madrid", 1, [], []],
  ["pt", "Portugal", "Lisbon", 1, [], ["Lisboa"]],
  ["ca", "Canada", "Ottawa", 1, [], []],
  ["mx", "Mexico", "Mexico City", 1, [], ["Ciudad de Mexico", "CDMX"]],
  ["br", "Brazil", "Brasília", 1, [], ["Brasilia"]],
  ["ar", "Argentina", "Buenos Aires", 1, [], []],
  ["ru", "Russia", "Moscow", 1, ["Russian Federation"], []],
  ["cn", "China", "Beijing", 1, ["People's Republic of China"], ["Peking"]],
  ["jp", "Japan", "Tokyo", 1, [], []],
  ["in", "India", "New Delhi", 1, [], ["Delhi"]],
  ["au", "Australia", "Canberra", 1, [], []],
  ["eg", "Egypt", "Cairo", 1, [], []],
  ["za", "South Africa", "Pretoria", 1, [], ["Cape Town", "Bloemfontein"]],
  ["gr", "Greece", "Athens", 1, [], []],
  ["tr", "Turkey", "Ankara", 1, ["Turkiye", "Türkiye"], []],
  ["nl", "Netherlands", "Amsterdam", 1, ["Holland", "The Netherlands"], []],
  ["ch", "Switzerland", "Bern", 1, [], ["Berne"]],
  ["se", "Sweden", "Stockholm", 1, [], []],
  ["no", "Norway", "Oslo", 1, [], []],
  ["ie", "Ireland", "Dublin", 1, [], []],
  ["pl", "Poland", "Warsaw", 1, [], ["Warszawa"]],
  ["kr", "South Korea", "Seoul", 1, ["Korea", "Republic of Korea"], []],
  ["sa", "Saudi Arabia", "Riyadh", 1, [], []],
  ["il", "Israel", "Jerusalem", 1, [], []],
  ["nz", "New Zealand", "Wellington", 1, [], []],

  // ---------- Level 2: well-known countries ----------
  ["at", "Austria", "Vienna", 2, [], ["Wien"]],
  ["be", "Belgium", "Brussels", 2, [], ["Bruxelles"]],
  ["dk", "Denmark", "Copenhagen", 2, [], []],
  ["fi", "Finland", "Helsinki", 2, [], []],
  ["is", "Iceland", "Reykjavik", 2, [], ["Reykjavík"]],
  ["ua", "Ukraine", "Kyiv", 2, [], ["Kiev"]],
  ["cz", "Czechia", "Prague", 2, ["Czech Republic"], ["Praha"]],
  ["hu", "Hungary", "Budapest", 2, [], []],
  ["ro", "Romania", "Bucharest", 2, [], []],
  ["hr", "Croatia", "Zagreb", 2, [], []],
  ["cu", "Cuba", "Havana", 2, [], ["La Habana"]],
  ["co", "Colombia", "Bogotá", 2, [], ["Bogota"]],
  ["cl", "Chile", "Santiago", 2, [], []],
  ["pe", "Peru", "Lima", 2, [], []],
  ["ve", "Venezuela", "Caracas", 2, [], []],
  ["th", "Thailand", "Bangkok", 2, [], []],
  ["vn", "Vietnam", "Hanoi", 2, [], []],
  ["ph", "Philippines", "Manila", 2, ["The Philippines"], []],
  ["id", "Indonesia", "Jakarta", 2, [], []],
  ["my", "Malaysia", "Kuala Lumpur", 2, [], ["KL"]],
  ["sg", "Singapore", "Singapore", 2, [], ["Singapore City"]],
  ["pk", "Pakistan", "Islamabad", 2, [], []],
  ["ir", "Iran", "Tehran", 2, [], []],
  ["iq", "Iraq", "Baghdad", 2, [], []],
  ["ma", "Morocco", "Rabat", 2, [], []],
  ["dz", "Algeria", "Algiers", 2, [], []],
  ["tn", "Tunisia", "Tunis", 2, [], []],
  ["ng", "Nigeria", "Abuja", 2, [], []],
  ["ke", "Kenya", "Nairobi", 2, [], []],
  ["et", "Ethiopia", "Addis Ababa", 2, [], []],
  ["ae", "United Arab Emirates", "Abu Dhabi", 2, ["UAE", "Emirates"], []],
  ["qa", "Qatar", "Doha", 2, [], []],
  ["jm", "Jamaica", "Kingston", 2, [], []],
  ["ec", "Ecuador", "Quito", 2, [], []],
  ["uy", "Uruguay", "Montevideo", 2, [], []],
  ["bg", "Bulgaria", "Sofia", 2, [], []],
  ["rs", "Serbia", "Belgrade", 2, [], ["Beograd"]],
  ["sk", "Slovakia", "Bratislava", 2, [], []],
  ["kp", "North Korea", "Pyongyang", 2, ["Democratic People's Republic of Korea", "DPRK"], []],
  ["af", "Afghanistan", "Kabul", 2, [], []],

  // ---------- Level 3: moderately known countries ----------
  ["bo", "Bolivia", "Sucre", 3, [], ["La Paz"]],
  ["py", "Paraguay", "Asunción", 3, [], ["Asuncion"]],
  ["gt", "Guatemala", "Guatemala City", 3, [], ["Guatemala"]],
  ["hn", "Honduras", "Tegucigalpa", 3, [], []],
  ["ni", "Nicaragua", "Managua", 3, [], []],
  ["cr", "Costa Rica", "San José", 3, [], ["San Jose"]],
  ["pa", "Panama", "Panama City", 3, [], ["Panama"]],
  ["do", "Dominican Republic", "Santo Domingo", 3, [], []],
  ["ht", "Haiti", "Port-au-Prince", 3, [], []],
  ["sv", "El Salvador", "San Salvador", 3, [], []],
  ["si", "Slovenia", "Ljubljana", 3, [], []],
  ["lt", "Lithuania", "Vilnius", 3, [], []],
  ["lv", "Latvia", "Riga", 3, [], []],
  ["ee", "Estonia", "Tallinn", 3, [], []],
  ["by", "Belarus", "Minsk", 3, [], []],
  ["al", "Albania", "Tirana", 3, [], ["Tirane"]],
  ["ba", "Bosnia and Herzegovina", "Sarajevo", 3, ["Bosnia"], []],
  ["mk", "North Macedonia", "Skopje", 3, ["Macedonia"], []],
  ["md", "Moldova", "Chișinău", 3, [], ["Chisinau", "Kishinev"]],
  ["ge", "Georgia", "Tbilisi", 3, [], []],
  ["am", "Armenia", "Yerevan", 3, [], []],
  ["az", "Azerbaijan", "Baku", 3, [], []],
  ["kz", "Kazakhstan", "Astana", 3, [], ["Nur-Sultan"]],
  ["uz", "Uzbekistan", "Tashkent", 3, [], []],
  ["mn", "Mongolia", "Ulaanbaatar", 3, [], ["Ulan Bator"]],
  ["np", "Nepal", "Kathmandu", 3, [], []],
  ["lk", "Sri Lanka", "Sri Jayawardenepura Kotte", 3, [], ["Colombo", "Kotte"]],
  ["bd", "Bangladesh", "Dhaka", 3, [], []],
  ["mm", "Myanmar", "Naypyidaw", 3, ["Burma"], ["Nay Pyi Taw"]],
  ["kh", "Cambodia", "Phnom Penh", 3, [], []],
  ["la", "Laos", "Vientiane", 3, [], []],
  ["jo", "Jordan", "Amman", 3, [], []],
  ["lb", "Lebanon", "Beirut", 3, [], []],
  ["sy", "Syria", "Damascus", 3, [], []],
  ["ye", "Yemen", "Sanaa", 3, [], ["Sana'a"]],
  ["om", "Oman", "Muscat", 3, [], []],
  ["kw", "Kuwait", "Kuwait City", 3, [], ["Kuwait"]],
  ["bh", "Bahrain", "Manama", 3, [], []],
  ["ly", "Libya", "Tripoli", 3, [], []],
  ["sd", "Sudan", "Khartoum", 3, [], []],
  ["gh", "Ghana", "Accra", 3, [], []],
  ["sn", "Senegal", "Dakar", 3, [], []],
  ["ci", "Ivory Coast", "Yamoussoukro", 3, ["Cote d'Ivoire", "Côte d'Ivoire"], ["Abidjan"]],
  ["cm", "Cameroon", "Yaoundé", 3, [], ["Yaounde"]],
  ["tz", "Tanzania", "Dodoma", 3, [], ["Dar es Salaam"]],
  ["ug", "Uganda", "Kampala", 3, [], []],
  ["zw", "Zimbabwe", "Harare", 3, [], []],
  ["zm", "Zambia", "Lusaka", 3, [], []],
  ["ao", "Angola", "Luanda", 3, [], []],
  ["mz", "Mozambique", "Maputo", 3, [], []],
  ["mg", "Madagascar", "Antananarivo", 3, [], []],
  ["lu", "Luxembourg", "Luxembourg City", 3, [], ["Luxembourg"]],
  ["mt", "Malta", "Valletta", 3, [], []],
  ["cy", "Cyprus", "Nicosia", 3, [], []],
  ["fj", "Fiji", "Suva", 3, [], []],

  // ---------- Level 4: lesser-known countries ----------
  ["bt", "Bhutan", "Thimphu", 4, [], []],
  ["bn", "Brunei", "Bandar Seri Begawan", 4, [], []],
  ["mv", "Maldives", "Malé", 4, [], ["Male"]],
  ["tl", "Timor-Leste", "Dili", 4, ["East Timor"], []],
  ["pg", "Papua New Guinea", "Port Moresby", 4, ["PNG"], []],
  ["tj", "Tajikistan", "Dushanbe", 4, [], []],
  ["kg", "Kyrgyzstan", "Bishkek", 4, [], []],
  ["tm", "Turkmenistan", "Ashgabat", 4, [], []],
  ["me", "Montenegro", "Podgorica", 4, [], []],
  ["xk", "Kosovo", "Pristina", 4, [], ["Prishtina"]],
  ["ad", "Andorra", "Andorra la Vella", 4, [], []],
  ["mc", "Monaco", "Monaco", 4, [], ["Monaco-Ville"]],
  ["li", "Liechtenstein", "Vaduz", 4, [], []],
  ["sm", "San Marino", "San Marino", 4, [], ["City of San Marino"]],
  ["va", "Vatican City", "Vatican City", 4, ["Holy See", "The Vatican"], []],
  ["bw", "Botswana", "Gaborone", 4, [], []],
  ["na", "Namibia", "Windhoek", 4, [], []],
  ["rw", "Rwanda", "Kigali", 4, [], []],
  ["bi", "Burundi", "Gitega", 4, [], ["Bujumbura"]],
  ["mw", "Malawi", "Lilongwe", 4, [], []],
  ["ml", "Mali", "Bamako", 4, [], []],
  ["ne", "Niger", "Niamey", 4, [], []],
  ["td", "Chad", "N'Djamena", 4, [], ["Ndjamena"]],
  ["mr", "Mauritania", "Nouakchott", 4, [], []],
  ["bf", "Burkina Faso", "Ouagadougou", 4, [], []],
  ["bj", "Benin", "Porto-Novo", 4, [], ["Cotonou"]],
  ["tg", "Togo", "Lomé", 4, [], ["Lome"]],
  ["gn", "Guinea", "Conakry", 4, [], []],
  ["sl", "Sierra Leone", "Freetown", 4, [], []],
  ["lr", "Liberia", "Monrovia", 4, [], []],
  ["ga", "Gabon", "Libreville", 4, [], []],
  ["cg", "Republic of the Congo", "Brazzaville", 4, ["Congo", "Congo-Brazzaville"], []],
  ["cd", "DR Congo", "Kinshasa", 4, ["Democratic Republic of the Congo", "DRC", "Congo-Kinshasa"], []],
  ["cf", "Central African Republic", "Bangui", 4, ["CAR"], []],
  ["so", "Somalia", "Mogadishu", 4, [], []],
  ["er", "Eritrea", "Asmara", 4, [], []],
  ["dj", "Djibouti", "Djibouti City", 4, [], ["Djibouti"]],
  ["ss", "South Sudan", "Juba", 4, [], []],
  ["gm", "Gambia", "Banjul", 4, ["The Gambia"], []],
  ["gw", "Guinea-Bissau", "Bissau", 4, [], []],
  ["gq", "Equatorial Guinea", "Malabo", 4, [], []],
  ["sz", "Eswatini", "Mbabane", 4, ["Swaziland"], ["Lobamba"]],
  ["ls", "Lesotho", "Maseru", 4, [], []],
  ["mu", "Mauritius", "Port Louis", 4, [], []],
  ["sc", "Seychelles", "Victoria", 4, [], []],
  ["cv", "Cape Verde", "Praia", 4, ["Cabo Verde"], []],
  ["km", "Comoros", "Moroni", 4, [], []],
  ["st", "São Tomé and Príncipe", "São Tomé", 4, ["Sao Tome and Principe"], ["Sao Tome"]],
  ["bz", "Belize", "Belmopan", 4, [], []],
  ["gy", "Guyana", "Georgetown", 4, [], []],
  ["sr", "Suriname", "Paramaribo", 4, [], []],
  ["tt", "Trinidad and Tobago", "Port of Spain", 4, ["Trinidad"], []],
  ["bs", "Bahamas", "Nassau", 4, ["The Bahamas"], []],
  ["bb", "Barbados", "Bridgetown", 4, [], []],
  ["kn", "Saint Kitts and Nevis", "Basseterre", 4, ["St Kitts and Nevis"], []],
  ["lc", "Saint Lucia", "Castries", 4, ["St Lucia"], []],
  ["vc", "Saint Vincent and the Grenadines", "Kingstown", 4, ["St Vincent"], []],
  ["gd", "Grenada", "St. George's", 4, [], ["Saint George's", "St Georges"]],
  ["dm", "Dominica", "Roseau", 4, [], []],
  ["ag", "Antigua and Barbuda", "St. John's", 4, ["Antigua"], ["Saint John's", "St Johns"]],
  ["ws", "Samoa", "Apia", 4, [], []],
  ["to", "Tonga", "Nuku'alofa", 4, [], ["Nukualofa"]],
  ["vu", "Vanuatu", "Port Vila", 4, [], []],
  ["sb", "Solomon Islands", "Honiara", 4, [], []],

  // ---------- Level 5: obscure territories, islands & micro-states ----------
  ["tv", "Tuvalu", "Funafuti", 5, [], []],
  ["nr", "Nauru", "Yaren", 5, [], []],
  ["ki", "Kiribati", "Tarawa", 5, [], ["South Tarawa"]],
  ["pw", "Palau", "Ngerulmud", 5, [], []],
  ["mh", "Marshall Islands", "Majuro", 5, [], []],
  ["fm", "Micronesia", "Palikir", 5, ["Federated States of Micronesia"], []],
  ["nu", "Niue", "Alofi", 5, [], []],
  ["tk", "Tokelau", "Fakaofo", 5, [], ["Atafu", "Nukunonu"]],
  ["ck", "Cook Islands", "Avarua", 5, [], []],
  ["pn", "Pitcairn Islands", "Adamstown", 5, ["Pitcairn"], []],
  ["wf", "Wallis and Futuna", "Mata-Utu", 5, [], ["Mata Utu"]],
  ["pf", "French Polynesia", "Papeete", 5, [], []],
  ["nc", "New Caledonia", "Nouméa", 5, [], ["Noumea"]],
  ["nf", "Norfolk Island", "Kingston", 5, [], []],
  ["cx", "Christmas Island", "Flying Fish Cove", 5, [], ["The Settlement"]],
  ["cc", "Cocos (Keeling) Islands", "West Island", 5, ["Cocos Islands", "Keeling Islands"], []],
  ["as", "American Samoa", "Pago Pago", 5, [], []],
  ["gu", "Guam", "Hagåtña", 5, [], ["Hagatna", "Agana"]],
  ["mp", "Northern Mariana Islands", "Saipan", 5, [], []],
  ["sh", "Saint Helena", "Jamestown", 5, ["St Helena"], []],
  ["fk", "Falkland Islands", "Stanley", 5, ["Falklands", "Malvinas"], ["Port Stanley"]],
  ["gs", "South Georgia and the South Sandwich Islands", "King Edward Point", 5, ["South Georgia"], ["Grytviken"]],
  ["bm", "Bermuda", "Hamilton", 5, [], []],
  ["ky", "Cayman Islands", "George Town", 5, [], ["Georgetown"]],
  ["tc", "Turks and Caicos Islands", "Cockburn Town", 5, ["Turks and Caicos"], []],
  ["vg", "British Virgin Islands", "Road Town", 5, ["BVI"], []],
  ["vi", "U.S. Virgin Islands", "Charlotte Amalie", 5, ["US Virgin Islands", "United States Virgin Islands"], []],
  ["ai", "Anguilla", "The Valley", 5, [], []],
  ["ms", "Montserrat", "Brades", 5, [], ["Plymouth"]],
  ["aw", "Aruba", "Oranjestad", 5, [], []],
  ["cw", "Curaçao", "Willemstad", 5, ["Curacao"], []],
  ["sx", "Sint Maarten", "Philipsburg", 5, [], []],
  ["mf", "Saint Martin", "Marigot", 5, ["St Martin"], []],
  ["bl", "Saint Barthélemy", "Gustavia", 5, ["St Barts", "Saint Barthelemy", "St Barthelemy"], []],
  ["pm", "Saint Pierre and Miquelon", "Saint-Pierre", 5, ["St Pierre and Miquelon"], ["Saint Pierre", "St Pierre"]],
  ["gl", "Greenland", "Nuuk", 5, [], ["Godthab", "Godthåb"]],
  ["fo", "Faroe Islands", "Tórshavn", 5, ["Faroes", "Faeroe Islands"], ["Torshavn"]],
  ["ax", "Åland Islands", "Mariehamn", 5, ["Aland Islands", "Aland"], []],
  ["gi", "Gibraltar", "Gibraltar", 5, [], ["Westside"]],
  ["im", "Isle of Man", "Douglas", 5, [], []],
  ["je", "Jersey", "Saint Helier", 5, [], ["St Helier"]],
  ["gg", "Guernsey", "Saint Peter Port", 5, [], ["St Peter Port"]],
  ["sj", "Svalbard", "Longyearbyen", 5, ["Svalbard and Jan Mayen"], []],
  ["yt", "Mayotte", "Mamoudzou", 5, [], []],
  ["re", "Réunion", "Saint-Denis", 5, ["Reunion"], ["Saint Denis", "St Denis"]],
  ["mq", "Martinique", "Fort-de-France", 5, [], ["Fort de France"]],
  ["gp", "Guadeloupe", "Basse-Terre", 5, [], ["Basse Terre"]],
  ["gf", "French Guiana", "Cayenne", 5, [], []],
  ["eh", "Western Sahara", "Laayoune", 5, [], ["El Aaiun", "El Aaiún"]],
];

const COUNTRIES = COUNTRY_ROWS.map(([code, name, capital, level, aliases, capitalAliases]) => ({
  code, name, capital, level,
  aliases: aliases || [],
  capitalAliases: capitalAliases || [],
}));

const LEVEL_NAMES = {
  1: "Beginner",
  2: "Traveler",
  3: "Explorer",
  4: "Geographer",
  5: "Cartographer",
};

const LEVEL_HINTS = {
  1: "World-famous countries everyone knows",
  2: "Well-known countries",
  3: "Moderately known countries",
  4: "Lesser-known countries & micro-states",
  5: "Obscure territories & remote islands",
};
